---
permalink: task-active-iq-virtual-machines.html 
sidebar: sidebar 
keywords: solidfire, active, iq, virtual, machines, vm 
summary: 'SolidFire Active IQ の[仮想マシン]ページについて説明します。' 
---
= 仮想マシン
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
選択したNetApp HCI クラスタのサイドパネルからアクセス可能な* Virtual Machines *ページでは、仮想マシン（VM）に関するCPUおよびストレージ関連のステータス情報を表示できます。


NOTE: 仮想マシン*ページは、NetApp HCI クラスタでのみ使用できます。

UIに表示されるVMデータのフィルタリングと概要について説明します。



== 仮想マシンの詳細を表示します

選択したクラスタのサイドパネルから使用可能な* Virtual Machines *（仮想マシン*）ページには、クラスタに関連付けられている各アクティブVMに関する情報が表示されます。

すべてのSolidFire Active IQ ページで使用できる従来のフィルタリング・オプションに加えて、[*仮想マシン*]ページにはクイック・フィルタ・ボタンがあり、一般的なVMの可用性状態を判別できます。

情報バーには、次のデータの概要が表示されます。

* 仮想マシン：ストレージクラスタに関連付けられたVMの数とさまざまな可用性状態。
* Status：VMの警告またはエラーの数。
* Provisioned Resources：ストレージクラスタに関連付けられているすべてのVMのストレージリソースとメモリリソースの合計です。


[cols="30,70"]
|===
| 見出し | 説明 


| 名前 | VMのフレンドリ名。 


| ステータス  a| 
VMの可用性ステータス：

* normal：VMは想定どおりに応答しています。
* 警告：警告が報告されています。詳細については、vSphereを参照してください。
* Critical：重大エラーが報告されています。詳細については、vSphereを参照してください。
* unknown：VMはアクセスできません。




| 電源の状態 | VMの電源がオン、オフ、または一時停止のいずれであるかを示します。 


| vCenterのIP | vCenter ServerのIPアドレス。 


| CPUの数 | 各VMのCPUの数。 


| ホストのメモリ使用量 | 仮想マシンで使用されているESXiホストのメモリ容量です。 


| CPU使用率 | アクティブに使用されている仮想CPUの割合。VM内の使用可能な合計CPUの割合です。 


| 使用済み容量 | VMストレージリソースが使用中である割合。 


| ディスクの最大レイテンシ | 検出されたディスクレイテンシの最大値（ミリ秒）。 


| アラーム | VMでトリガーされたvSphereアラームの数。 
|===


== 詳細については、こちらをご覧ください

https://www.netapp.com/support-and-training/documentation/["ネットアップの製品マニュアル"^]
