---
permalink: task_active_iq_replication.html 
sidebar: sidebar 
keywords: solidfire, active, iq, replication 
summary: 'SolidFire Active IQ の[複製]ページについて説明します。' 
---
= レプリケーション
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
選択したクラスタのサイドパネルからアクセス可能な* Replication *ページには、クラスタペアとボリュームペアに関する情報が表示されます。

クラスタペアとボリュームペアのページに関する詳細を確認します。

* ,クラスタペア
* ,ボリュームペア




== クラスタペア

選択したクラスタの* Replication *>* Cluster Pairs *ページで、クラスタペアに関する次の情報を表示できます。

[cols="30,70"]
|===
| 見出し | 説明 


| クラスタペアのID | クラスタペアの作成時に指定したID番号。 


| リモートクラスタ名 | ペアのリモートクラスタの名前。 


| リモートMVIP | リモートクラスタの管理仮想IP。 


| ボリュームのレプリケート | ペアクラスタにレプリケートされているボリュームの数です。 


| ステータス | クラスタペアの状態。 


| UUID | Universally Unique Identifierの略。 
|===


== ボリュームペア

選択したクラスタの* Replication *>* Volume Pairs *ページで、ボリュームペアに関する次の情報を表示できます。

[cols="30,70"]
|===
| 見出し | 説明 


| ボリューム ID | ボリュームの作成時に指定したID番号。 


| アカウント ID | ボリュームに割り当てられているアカウントのID。 


| ボリュームステータス | レプリケートするボリュームの状態。 


| レプリケーションモード | ボリュームペアに対して選択されているモードのタイプ。 


| 方向（ Direction ）  a| 
ボリュームデータの方向を示します。

* Source：クラスタの外部のターゲットにデータを書き出していることを示します。
* Target：外部のソースからローカルボリュームにデータが書き込まれていることを示します。




| 非同期遅延  a| 
ボリュームが最後にリモートクラスタと同期されてからの時間。ボリュームがペアリングされていない場合、値は null です。


NOTE: レプリケーションがアクティブな状態のターゲットボリュームでは常に0（ゼロ）です。レプリケーション中、ターゲットボリュームはシステムを認識し、非同期時間が常に正確であるものとします。



| リモートクラスタ | ボリュームが配置されているリモートクラスタの名前。 


| リモートボリュームID | リモートクラスタのボリュームのボリューム ID 。 
|===


== 詳細については、こちらをご覧ください

https://www.netapp.com/support-and-training/documentation/["ネットアップの製品マニュアル"^]
